### ISSUE TITLE
Query regarding the Multi-frame Map-free benchmark

### ISSUE THREAD

**Issue by suraj-avataar** [nianticlabs/mickey#10]
Hi,

Thank you again for the work, I have a query regarding the benchmark. MicKey only takes in two images and provides the corresponding output. However, I see that MicKey is part of the leaderboard in the Multi-frame, Map-free visual Relocalization benchmark ([link](https://research.nianticlabs.com/mapfree-reloc-benchmark/leaderboard?t=multi9)). According to a previous comment on one of the issues, MicKey has not yet been tested on multiple views. ([link](https://github.com/nianticlabs/mickey/issues/8#issuecomment-2134732930))

Could you explain how Mickey is part of the leaderboard/ What that benchmark means? 

Thanks,
Suraj

**Comment by axelBarroso** [comment]
Hello!

That is a very simple baseline. Even though we have multiple images as input, we ignore all but one. Hence, this is the regular MicKey setup, only using the reference and query image.

This baseline was meant to show how a single query frame works and give the basis to improve upon it.  

Hope this helps!

**Comment by suraj-avataar** [comment]
I see, Is the selected query image at random from the set of images or is the best-performing image chosen?

**Comment by axelBarroso** [comment]
It is running the last frame (the one that the benchmark evaluates). Using the most-confident frame and then using the tracking pose to the desired coordinate system could potentially improve those results.

**Comment by suraj-avataar** [comment]
Thank you for the clarification
