### ISSUE TITLE
Predicting X and Y coordinates directly.

### ISSUE THREAD

**Issue by JayKarhade** [nianticlabs/mickey#14]
Hi, 

Really exciting work!

 I had a quick question - did you consider directly predicting the X and Y coordinates in 3D instead of the offsets and using the intrinsics to project them?

**Comment by axelBarroso** [comment]
Hello! 
We did not try that, but it sounds very interesting! I see that option closer to what DUSt3R/MASt3R does, so I would be keen to learn how that variant works. Thanks for the interest!

**Comment by JayKarhade** [comment]
Thanks! I'll let you know how the training goes :)
