### ISSUE TITLE
Minor bug in e2eprobabilisticprocrustes

### ISSUE THREAD

**Issue by JayKarhade** [nianticlabs/mickey#16]
Hi! 

There seems to be a minor bug at 

https://github.com/nianticlabs/mickey/blob/06e62e5a119bd7a02c18a3c2759e2e68b907492c/lib/models/MicKey/modules/utils/probabilisticProcrustes.py#L176

The variables R, t_metric, best_inliers are initialized only if num_valid_h > 0, and this runs into an error if num_valid=0.

**Comment by axelBarroso** [comment]
Hello!

Thanks for spotting that, it has now been fixed. Thank you!
