### ISSUE TITLE
A naive question about depth prediction

### ISSUE THREAD

**Issue by Hippogriff** [nianticlabs/mickey#2]
I am new to MVS research, so pardon me if the question is naive.
How do you ensure that the predicted depth is a correct metric depth? In other words, how do you ensure the depth predictions have correct scale. AFAIK you do not supervise your depth maps directly.

**Comment by axelBarroso** [comment]
Thanks for the question!

Yes, you are correct, we do not supervise the depth maps directly. However, the depth maps are used to predict the 3D positions of the keypoints, which in turn are used to compute the relative poses. Our pose supervision uses metric poses as GT, and hence, to minimize the loss, our network needs to provide valid metric depth estimations. In short, metric depth comes from the fact that the GT poses are in metric space.

One additional note here is that we only need accurate depth where keypoints are found, contrary to standard depth estimators that try to be accurate everywhere.

**Comment by axelBarroso** [comment]
Closing this issue since it has been inactive for over a week - do please open it again if you have more questions. Thanks!

**Comment by Hippogriff** [comment]
Great explanation. Thank you!
