### ISSUE TITLE
Minor bugs in demo_inference.py file

### ISSUE THREAD

**Issue by sajal-sony** [nianticlabs/mickey#20]
Hi,

I would like to report some changes I had to make to the code in the repository to get the `demo_inference.py` to run on custom examples. The changes I made were :

1. `demo_inference.py` : Lines 105 and 106 seem to be hardcoded to the `toy_example` image names, just changing this to extract image name from reference and destination image should be good.

2. `lib/models/MicKey/compute_pose.py `: In the `forward `function for `MickeyRelativePose` class the code for returning `inliers_list` has been commented out (line 26,34), `inliers_list` seems to be necessary for the `create_point_cloud_from_inliers` function. As my only intention right now was to visualize the results for my own images, I just restored the commented out code for returning `inliers_list` (line 26,34)  and commented out the "if inliers is not needed" code on line 29. 

I hope these small changes can be made so that the demo can work without any tinkering. 

Thanks!

**Comment by axelBarroso** [comment]
Hello,

Thanks a lot for these suggestions, that was really helpful. We have just pushed the changes so that people can run the demo without errors in the future. Thank you!
