### ISSUE TITLE
cross-domain image matching

### ISSUE THREAD

**Issue by pbmsmtmt** [nianticlabs/mickey#3]
Thanks for your work!
I want to know if this work can do cross-domain image matching? For example, visible light images and infrared images?

**Comment by axelBarroso** [comment]
Hello! 

The network was trained on a single, and very specific, domain: outdoor images captured by pedestrians. 

We tried "cross-domain" matching, but it was done between indoor (ScanNet) and outdoors (Map-free). We show in the supplementary that the network generalized fairly well there, but both domains are still _visible light_ images. 

MicKey has not seen any such examples, eg, infrared images, during training and I would not be surprised if it does not work very well.

**Comment by pbmsmtmt** [comment]
Thank you for your answer. I would like to ask if the input is an image pair, one as a reference image and the other as a source image, can the source image be converted to the perspective of the reference image through the Mickey model? Similar to solving the transformation matrix between the two? Please tell me how to implement it in the code, because the demo seems to be more inclined to output the depth map and the confidence score map, but it does not give me the conversion result. Looking forward to your reply!
