### ISSUE TITLE
How to perform image pair matching

### ISSUE THREAD

**Issue by pbmsmtmt** [nianticlabs/mickey#4]
Thank you for your work. I would like to ask if the input is an image pair, one as a reference image and the other as a source image, can the source image be converted to the perspective of the reference image through the Mickey model? Similar to solving the transformation matrix between the two? Please tell me how to implement it in the code, because the demo seems to be more inclined to output the depth map and the confidence score map, but it does not give me the conversion result. Looking forward to your reply!

**Comment by axelBarroso** [comment]
Hello! 

MicKey uses one single image as input, and as you mentioned, it returns:
- Keypoint scores.
- Keypoint depth and 2D offset (we can obtain the 3D coordinates from them, see Eq. 1 main paper). 
- Keypoint descriptors.

We provide the [demo code](https://github.com/nianticlabs/mickey/blob/main/demo_inference.py) to compute the metric relative pose (R, t), given two images: the reference and the query image. 

The relative pose can be used to warp one image into the other. You would need to use the depth maps for that too. Note that depth maps are not accurate in the whole image, but only where the keypoint score is high.

**Comment by axelBarroso** [comment]
Closing this issue since it has been inactive for over a week - do please open it again if you have more questions. Thanks!
