### ISSUE TITLE
Basic question on resizing images

### ISSUE THREAD

**Issue by tianyilim** [nianticlabs/mickey#6]
I'm a beginner with ML models for perception, so apologies if this question is basic.

In `demo_inference.py` there is a way to read images, which are resized to a default size of `(540, 720)`. Then, there is a `read_intrinsics` function with a default parameter `resize`.

My question is: If input images do not have a size of `(540, 720)`, does the resizing for the intrinsics need to be applied too? If not, when would one use it?

**Comment by axelBarroso** [comment]
Hello! 

Thank you for the interest in our work! 

You are right, we set the default value (540, 720) to the image size of the Map-free dataset, but we could use any other size.

The idea is that if the image goes under a resizing, the intrinsic parameters need to be rectified. And just to clarify, MicKey does not limit input images to (540, 720) resolution, but accepts any input image size. 

Please, let me know if this helps. Thanks!

**Comment by tianyilim** [comment]
This helps a little, but I would just like to confirm my understanding: 

Is it correct that the intrinsics parameters must match any resizing of the input image?

I ask because the `demo_inference` script resizes images by default to (540, 720) but does not correct the intrinsic scale by default. Therefore, an image would be passed to MicKey would have incorrect intrinsics (corresponding to the original size of the image).

**Comment by axelBarroso** [comment]
> Is it correct that the intrinsics parameters must match any resizing of the input image?

Yes, you are right. Same resizing needs to happen to the image and to the intrinsics. We have corrected the demo script to ensure that. Thanks a lot for the feedback! 

Do please reopen the issue if you have any further questions, thanks again!
