### ISSUE TITLE
How to get overlaps.npz in customer datasets

### ISSUE THREAD

**Issue by jywu511** [nianticlabs/mickey#7]
Hi, thanks for your great work. When I used my dataset, how can I get the overlaps.npz before training? I found it is important. Thanks!

Best regards

**Comment by axelBarroso** [comment]
Hello! The overlaps.npz was computed originally in the [Map-free dataset](https://storage.googleapis.com/niantic-lon-static/research/map-free-reloc/MapFreeReloc-ECCV22-paper.pdf). To obtain the overlap, they had to build the 3D models (using COLAMP). 

Given two images (im0 and im1) and the 3D point cloud, you can check how many of the 3D points can be projected in both images. The overlap is the ratio between shared_3d_points and max(projected_3d_points_0, projected_3d_points_1). You can see more details in the [Map-free supplementary material](https://fff6adf0b1d5d22204880a79c270c2174b64dbaac1f306c17678dbf-apidata.googleusercontent.com/download/storage/v1/b/niantic-lon-static/o/research%2Fmap-free-reloc%2FMapFreeReloc-ECCV22-supplemental.pdf?jk=ASOpP9iSQH-t0QDtW06e7KHUJHSA537J0MNjAorGz2n95u3U21DsXL80qq73scmhsgkrNonodWk6D1ymK6bSmuNn3eydepxcaNR7Dml4MwkPBvjkBh0klfJTmHUinXfBfGcWIuXpfBsRPCw-lqeZ8QU6da3Jhi2PEBRDo78mCkFh48FvhqTzNrgQl9TywG7voV35J8wSb4hwyEO-WYmgLNTkYEVAwIu0RMjxKUO9innkkwms816U6lk9miFU_B2aeIaPjhlByEJYeeGym3vwVdYfdQyibO7uE6IjMcXOjdOfRZM17bSgwxsa9_kJgXFdlPzjgfr5BJHhCQVEWzPWvhlrwtU42yzY1dvYtGSemkHacRk7LyP9dqINPd8mqsygB3z2afydFRlpR7htjH3ZSTuWEUKpBySFeBgA5W9AB4EmcAKSF04upMTVVtKummalXB7G6mu7QE_IuuwzPFl3JFmMgrlFVpCZ5gdfEb4CYP_eKDa7Lkce4IpEidUeecf3LC5whOQ8SKhJHcf2Obk1fzzlXr0rlRoS9d5gPA-eZ03Vw7MFGTaFMn2FG0sDsscZtt28b6KoJaNXiGmvlyeNVhfCJRqoJRJcJQoWMkqPovQfxnxf2jw7WKceUEmbLSkYpmmdSqL7EgR-nllR3bkWHgPpXWJfA4tcDzc2otTK6RJDG1w3J6Nwy3QLVxI8AvMUTOxQ82eUhS7YFcdCwKg4qSng1VdhbaDzJavXZ9c2A2vujbRl_1AxxkfnBL7_sxRsq7hpCvtoaL5LB7wc1oYBbIMETX7wLVAGYhh9DRba4YlSsNLcrnAkF_0Vlm1ZXfXHlmtDQa_GUyPlQuA7IPoCWcsyFI5abTNza-EqP5z_uQCfOQueuS-al0FcnCsSTc7LQS5jkBVT_tad7OU13uHk16buzGyW3n0x_TzFD-gVddz28EwyKi3To3HRVO-096rKqs1ZrCbnvTqCIMXOsmjWpqZs_mdwJd54dCQ0CCMMsMQlRUhCN0u9veCtwZ5h1fABBND_1SPsWcLOBgNICp_zY_9vNGNIXbnSwJEzIhOhPKb0UXN_gS6tqwBXcYyBSTRh7lige59qTWxBP_uqmgPOLU7q29LSwDaavUDYw50-UX38AFsn4W3-Pxv5HB55QoyZsN2NqhIjWR_Vrs8llq1zfF7o3P_SzMcl4LAwjVIS2WIsfb9NTks-1A&isca=1) (look for _Overlap Score_ section). 

> I found it is important.

Could you give more details on why overlaps are important? Are you using the curriculum learning configuration? Hopefully, I can assist a bit more.

**Comment by jywu511** [comment]
Thanks for your response! I have understood the way  getting overlaps.npz. However, if I want to train the mickey model with my own dataset, how should I generate my own overlaps.npz? Thanks.

**Comment by axelBarroso** [comment]
Hello! 

Overlaps.npz are obtained with COLMAP (see my previous comment).

Regarding your dataset, do you have a list of images you want to use for training? And if so, do you know if they are solvable (or have any overlap)? If that is the case, I think that using the curriculum learning approach of MicKey should be enough for training. For instance, if you think that only 70% of the pairs are solvable, you could set 70 in [here](https://github.com/nianticlabs/mickey/blob/main/config/MicKey/curriculum_learning.yaml#L84). 
That will let MicKey know that only the top 70% of the image pairs should be solvable, and that it can discard all the others.

**Comment by jywu511** [comment]
Thanks for your response!
