### ISSUE TITLE
How to get poses for more than 2 images (in the same coordinate world)

### ISSUE THREAD

**Issue by suraj-avataar** [nianticlabs/mickey#8]
Hi, Thank you for the work and for making the code available. For a use case, I would like to run the model for more than two images and get the poses of the camera. The naive way was to run with the reference image fixed while the destination changes. But that did not work. Could you comment on how I could run the model on more than 2 images and use the output poses?

**Comment by axelBarroso** [comment]
Hello! 

We have only experimented with two images, multi-view is still something we need to explore. Having said that, I would have started doing the same that you did, using one image as the anchor and computing the relative poses of all the other images _wrt_ the anchor. 

Can you give some details as to why that did not work? Is it an accuracy problem, or does it seem like the coordinate system is all wrong? 

Thanks!

**Comment by suraj-avataar** [comment]
It could be an accuracy issue looking at the GT and the predicted poses in the attached image. The GT poses form a semi-circle, the expectation was that predicted poses follow the same to some degree. But some of the images that are close to the anchor (The camera at the origin) also had issues). 

![mickey_git_issue](https://github.com/nianticlabs/mickey/assets/166009721/04fbd0f3-a308-48cc-a1e6-1b987aa16e36)

Any hints on what could be the reason for this? 

(Edit)
This is a separate doubt, but is the returned R,t the rotation of cam1 wrt cam2 or the other way around?

Thanks

**Comment by axelBarroso** [comment]
Closing this issue since it was resolved in another issue - do please open it again if you have more questions. Thanks!
