### ISSUE TITLE
Run on images from different cameras?

### ISSUE THREAD

**Issue by antithing** [nianticlabs/mickey#9]
Hi, can this code be used to calculate the extrinsics between two images from different camera types? 

Eg, a DSLR and a GoPro, for example.

Or does it assume the same camera and lens for an image pair?

Thanks!

**Comment by axelBarroso** [comment]
Hello! 

MicKey requires intrinsics during inference time, they are used to lift the 2D points to 3D. If you know the intrinsics of the two images, it should work. 

Just a small note, MicKey's training is limited in terms of data. We use the Map-free dataset, which although have many different scenes, all have similar intrinsics. And besides, only smartphone images are in the dataset. 

Thanks!

**Comment by axelBarroso** [comment]
Closing this issue since it has been inactive for over a month - do please open it again if you have more questions. Thanks!
